# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'json'

# Parse the json configuration
$settings = {}

if File.exists?(File.expand_path ENV['CONFIG_FILE'])
  $settings = JSON.parse(File.read(File.expand_path ENV['CONFIG_FILE']))
else
  if File.exists?(File.expand_path "./config-default.json")
    $settings = JSON.parse(File.read(File.expand_path "./config-default.json"))
  end
end

Vagrant.configure(2) do |config|
	config.vm.box = "dummy"
	config.vm.provider :aws do |aws, override|
    aws.tags = {
      'Name' => 'Benchmarker FedBench Client'
    }
		aws.access_key_id = ENV['AWS_ACCESS_KEY']
    aws.secret_access_key = ENV['AWS_SECRET_KEY']
#   aws.session_token = "SESSION TOKEN"
    aws.keypair_name = ENV['SSH_KEYNAME']
		aws.region = "us-east-1"

		aws.security_groups = $settings['security_groups']
		aws.subnet_id = $settings['subnet']
#		aws.elastic_ip = "true"
		aws.associate_public_ip = "true"
		aws.ebs_optimized = "true"
		aws.ami = $settings['ami_benchmarker']

		aws.instance_type = "c3.xlarge"
    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = ENV['SSH_KEY'] #should not be necessary as aws key is given
	end

  config.vm.define 'Benchmarker'

  instance.vm.provision "chef_solo" do |chef|
    chef.json = {
      :endpoints => $settings['endpoints'],
    }

    chef.cookbooks_path = "../chef/cookbooks"
    chef.add_recipe "client"

  end
end
