# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'json'

# Parse the json configuration
$settings = {}

if File.exists?(File.expand_path ENV['CONFIG_FILE'])
  $settings = JSON.parse(File.read(File.expand_path ENV['CONFIG_FILE']))
else
  if File.exists?(File.expand_path "./config-default.json")
    $settings = JSON.parse(File.read(File.expand_path "./config-default.json"))
  end
end

$script = "sudo mkdir /home/ubuntu/server-logs\n"
$settings['endpoints'].each { |endpt|
  $script += "sudo scp -o StrictHostKeyChecking=no -i /vagrant/aws ubuntu@#{endpt['ip']}:/vagrant/*.csv /home/ubuntu/server-logs/\n"
  $script += "sudo scp -o StrictHostKeyChecking=no -r -i /vagrant/aws ubuntu@#{endpt['ip']}:ldf-server/summaries/ /home/ubuntu/server-logs/\n"
  $script += "sudo scp -o StrictHostKeyChecking=no -r -i /vagrant/aws ubuntu@#{endpt['ip']}:ldf-server/logs/access.log /home/ubuntu/server-logs/#{endpt['ip']}-access.log\n"
}

Vagrant.configure(2) do |config|
	config.vm.box = "dummy"
	config.vm.provider :aws do |aws, override|
    aws.tags = {
      'Name' => 'Benchmarker FedBench Client'
    }
		aws.access_key_id = ENV['AWS_ACCESS_KEY']
    aws.secret_access_key = ENV['AWS_SECRET_KEY']
#   aws.session_token = "SESSION TOKEN"
    aws.keypair_name = ENV['SSH_KEYNAME']
		aws.region = "us-east-1"

		aws.security_groups = $settings['security_groups']
		aws.subnet_id = $settings['subnet']
#		aws.elastic_ip = "true"
		aws.associate_public_ip = "true"
		aws.ebs_optimized = "true"
		aws.ami = $settings['ami_benchmarker']

		aws.instance_type = "c3.xlarge"
    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = ENV['SSH_KEY'] #should not be necessary as aws key is given
	end

  config.vm.define 'Benchmarker'
  config.vm.provision "shell", inline: $script
end
