# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'json'

# Parse the json configuration
settings = {}

if File.exists?(File.expand_path "./config.json")
  settings = JSON.parse(File.read(File.expand_path "./config.json"))
fi

$install_virtuoso = 'false'

def provision_server (config, endpt)
  config.vm.define endpt.name do |instance|
    instance.vm.provider :aws do |aws, override|
      aws.private_ip_address = endpt.ip
    end

    instance.vm.provision "chef_solo" do |chef|
		  chef.json = {
			  :datasets => endpt.datasets,
			  :install_virtuoso => $install_virtuoso,
        :virtuoso => settings.virtuoso
		  }

		  chef.cookbooks_path = "../chef/cookbooks"
      chef.add_recipe "fedbench_virtuoso"
    end
  end
end

Vagrant.configure(2) do |config|
	config.vm.box = "dummy"

	config.vm.provider :aws do |aws, override|
		aws.access_key_id = ENV['AWS_ACCESS_KEY']
    aws.secret_access_key = ENV['AWS_SECRET_KEY']
#   aws.session_token = "SESSION TOKEN"
    aws.keypair_name = "FedBench"
		aws.region = "us-east-1"

		aws.security_groups = settings.security_groups
		aws.subnet_id = settings.subnet
#		aws.elastic_ip = "true"
		aws.associate_public_ip = "true"

#		The following image has already virtuoso installed.
		aws.ami = settings.ami

		aws.instance_type = "c3.xlarge"
    override.ssh.username = "ubuntu"
#   override.ssh.private_key_path = "FedBench.pem" #should not be necessary as aws key is given
	end

	settings.endpoints.each { |endpt|
		provision_server(config, endpt)
	}
end
